/*
DEWALD 
SCRIPT TO EXECUTE DIMENION ACCOUNT SELECTIONS
*/
Create PROCEDURE DIMACCENT -- EXEC DIMACCSEL '002-1' , '25054
(
	@FCY VARCHAR(25),
	@GAC VARCHAR(25),
	@PRM VARCHAR(25),
	@VALUER varchar(25)
)
AS
BEGIN
WITH ORGSTRUCTURE (SITE, COMPANY, LEDGER) AS
(
SELECT F.FCY_0, F.LEGCPY_0,A.LED_0
FROM DEV00.FACILITY F
	INNER JOIN DEV00.COMPANY C ON F.LEGCPY_0 = C.CPY_0
	INNER JOIN DEV00.GACM A ON C.ACM_0 = A.GCM_0
),

LEDGERDIMTYPES (LEDGER,DIMTYPE) AS
(
	SELECT LED_0,DIE_0 AS DIMTYPE
	FROM DEV00.GLED
	UNION 

	SELECT LED_0,DIE_1 AS DIMTYPE
	FROM DEV00.GLED
	UNION

	SELECT LED_0,DIE_2 AS DIMTYPE
	FROM DEV00.GLED
	UNION 

	SELECT LED_0,DIE_3 AS DIMTYPE
	FROM DEV00.GLED
	UNION

	SELECT LED_0,DIE_4 AS DIMTYPE
	FROM DEV00.GLED
),

DIMVALUES (DIM,DIMTYPE,SITE,DESCRIPT) AS
(
   SELECT CCE_0,DIE_0,FCY_0,DES_0
   FROM DEV00.CACCE
   WHERE DIE_0 = @PRM and CCE_0 = @VALUER
),

VALIDACCOUNTS (DIMTYPE,DIM,LED,ACC) AS
(
   SELECT YDIE_0,YCCE_0,YLED_0,YACC_0
   FROM DEV00.YPCCACC
   WHERE YLED_0 <> '' AND YDIE_0 = @PRM
)

--#### - Original Selection Statement : SELECT O.SITE,O.LEDGER,L.DIMTYPE,C.DIM,A.ACC, C.DESCRIPT
SELECT O.LEDGER,L.DIMTYPE,C.DIM,C.DESCRIPT
FROM ORGSTRUCTURE O
	INNER JOIN LEDGERDIMTYPES L ON O.LEDGER = L.LEDGER
	INNER JOIN DIMVALUES C ON C.DIMTYPE = L.DIMTYPE
	LEFT OUTER JOIN VALIDACCOUNTS A ON C.DIMTYPE = A.DIMTYPE AND C.DIM = A.DIM
WHERE O.SITE = @FCY AND ACC = @GAC

UNION ALL

SELECT O.LEDGER,L.DIMTYPE,C.DIM,C.DESCRIPT
FROM ORGSTRUCTURE O
	INNER JOIN LEDGERDIMTYPES L ON O.LEDGER = L.LEDGER
	INNER JOIN DIMVALUES C ON C.DIMTYPE = L.DIMTYPE
	LEFT OUTER JOIN VALIDACCOUNTS A ON C.DIMTYPE = A.DIMTYPE AND C.DIM = A.DIM
WHERE O.SITE = @FCY AND ACC IS NULL

END