WITH HEADERGROUP (FCY_0, CPY_0, ACM_0, LED_0, COA_0, DIE_0, DIE_1, DIE_2, DIE_3, DIE_4) as
(
	Select FCY.FCY_0, CPY.CPY_0, CPY.ACM_0, LED.LED_0, LED.COA_0, LED.DIE_0, LED.DIE_1, LED.DIE_2, LED.DIE_3, LED.DIE_4
	From FACILITY FCY
	inner join COMPANY CPY on CPY.MAIFCY_0 = FCY.FCY_0 and FCY.LEGCPY_0 = CPY.CPY_0
	inner join GACM GCM on GCM.GCM_0 = CPY.ACM_0
	inner join GLED LED on LED.LED_0 = GCM.LED_0
	Where FCY.FCY_0 = '001-1'
),

DIM0 (DIE_0, CCE_0) as
(
	Select CCE.DIE_0,  CCE.CCE_0
	From GDIE DIE
	inner join CACCE CCE on CCE.DIE_0 = DIE.DIE_0
)

Select FCY_0, CPY_0, ACM_0, LED_0, COA_0, DIM1.CCE_0, DIM2.CCE_0, DIM3.CCE_0, DIM4.CCE_0, DIM5.CCE_0
From HEADERGROUP GRP
inner join DIM0 DIM1 on GRP.DIE_0 = DIM1.DIE_0
inner join DIM0 DIM2 on GRP.DIE_1 = DIM2.DIE_0
inner join DIM0 DIM3 on GRP.DIE_2 = DIM3.DIE_0
inner join DIM0 DIM4 on GRP.DIE_3 = DIM4.DIE_0
inner join DIM0 DIM5 on GRP.DIE_4 = DIM5.DIE_0