CREATE TABLE #ZTEMP_ERR 
(
	[UID] INTEGER IDENTITY(1,1) NOT NULL,
	[OBJ_TYP]  VARCHAR(50) NOT NULL,
	[ERR_ORIG] VARCHAR(100) NOT NULL,
	[ERR_STAT] VARCHAR(100) NOT NULL,
	[ERR_MESS] VARCHAR(250) NOT NULL
)
GO


--# VARIABLE DECLARATIONS
DECLARE @BATCHNO VARCHAR(50),
		@ERR INTEGER,
		@ERRMSG VARCHAR(250),
		-- DETAIL VALIDATIONS
		@JOU VARCHAR(5),
		@GTE VARCHAR(5),
		@FCY VARCHAR(5),
		@CPY VARCHAR(5),
        @ACM VARCHAR(5),
        @COA VARCHAR(5),
        @LED VARCHAR(5),
        @DIE0 VARCHAR(5),
        @DIE1 VARCHAR(5),
        @DIE2 VARCHAR(5),
        @DIE3 VARCHAR(5),
        @DIE4 VARCHAR(5),
		@CCE0 VARCHAR(5),
        @CCE1 VARCHAR(5),
        @CCE2 VARCHAR(5),
        @CCE3 VARCHAR(5),
        @CCE4 VARCHAR(5),
		@CPYACT INTEGER

DECLARE BBFCY_CURSOR CURSOR FOR 
SELECT YBATNBR_0, YFCY_0, YBATTYP_0, YJOU_0, YCCE0_0, YCCE1_0, YCCE2_0, YCCE3_0, YCCE4_0 FROM YBBDETAIL --WHERE YBATNBR_0 = @BATCHNO

OPEN BBFCY_CURSOR  
FETCH NEXT FROM BBFCY_CURSOR INTO @BATCHNO, @FCY, @GTE, @JOU, @CCE0, @CCE1, @CCE2, @CCE3, @CCE4 

WHILE @@FETCH_STATUS = 0  
BEGIN  

	SELECT	@CPY =  CPY.CPY_0, 
			@ACM = CPY.ACM_0, 
			@LED = LED.LED_0, 
			@COA = LED.COA_0, 
			@DIE0 = LED.DIE_0, 
			@DIE1 = LED.DIE_1, 
			@DIE2 = LED.DIE_2, 
			@DIE3 = LED.DIE_3, 
			@DIE4 = LED.DIE_4, 
			@CPYACT = CPY.YCPYACT_0
	FROM FACILITY FCY
	INNER JOIN COMPANY CPY ON CPY.MAIFCY_0 = FCY.FCY_0 AND FCY.LEGCPY_0 = CPY.CPY_0
	INNER JOIN GACM GCM ON GCM.GCM_0 = CPY.ACM_0
	INNER JOIN GLED LED ON LED.LED_0 = GCM.LED_0
	WHERE FCY.FCY_0 = @FCY

	--> 01 : COMPANY NOT ACTIVE	
	IF @CPYACT <> 2 
	BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@CPYACT,'COMPANY NOT ACTIVE')
	END

	-->02 : JOURNAL AS BB
	IF (SELECT YBUSBAT_0 FROM GJOURNAL WHERE JOU_0 = @JOU) <> 1
	BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@JOU,'JOURNAL NOT MARKED AS BB')	
	END

	-->03 : ENTRY TYPE AS BB
	IF (SELECT YBUSBAT_0 FROM GTYPACCENT WHERE TYP_0 = @GTE) <> 1
	BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@GTE,'ENTRY TYPE NOT MARKED AS BB')	
	END

	-->04 : DIMENSIONS
	DECLARE @FCYC VARCHAR(5),
			@FCYF VARCHAR(5)

	  SELECT @FCYC = C.FCY_0, @FCYF = F.FCY_0
	  FROM CACCE C
	  LEFT OUTER JOIN FACGROUP F ON C.FCY_0 = F.CPY_0
	  WHERE C.CCE_0 = @CCE0 AND C.DIE_0 = @DIE0
 
	  IF @FCYC <> '' OR @FCYF <> @FCY OR @FCYC <> @FCY and @CCE0 <> ''
	  BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@CCE0,'RESTRICTED DIMENSION')
	  END

	  SELECT @FCYC = C.FCY_0, @FCYF = F.FCY_0
	  FROM CACCE C
	  LEFT OUTER JOIN FACGROUP F ON C.FCY_0 = F.CPY_0
	  WHERE C.CCE_0 = @CCE1 AND C.DIE_0 = @DIE1
 
	  IF @FCYC <> '' OR @FCYF <> @FCY OR @FCYC <> @FCY and @CCE1 <> ''
	  BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@CCE1,'RESTRICTED DIMENSION')
	  END

	  SELECT @FCYC = C.FCY_0, @FCYF = F.FCY_0
	  FROM CACCE C
	  LEFT OUTER JOIN FACGROUP F ON C.FCY_0 = F.CPY_0
	  WHERE C.CCE_0 = @CCE2 AND C.DIE_0 = @DIE2
 
	  IF @FCYC <> '' OR @FCYF <> @FCY OR @FCYC <> @FCY and @CCE2 <> ''
	  BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@CCE2,'RESTRICTED DIMENSION')
	  END

	  SELECT @FCYC = C.FCY_0, @FCYF = F.FCY_0
	  FROM CACCE C
	  LEFT OUTER JOIN FACGROUP F ON C.FCY_0 = F.CPY_0
	  WHERE C.CCE_0 = @CCE3 AND C.DIE_0 = @DIE3
 
	  IF @FCYC <> '' OR @FCYF <> @FCY OR @FCYC <> @FCY and @CCE3 <> ''
	  BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@CCE3,'RESTRICTED DIMENSION')
	  END

	  SELECT @FCYC = C.FCY_0, @FCYF = F.FCY_0
	  FROM CACCE C
	  LEFT OUTER JOIN FACGROUP F ON C.FCY_0 = F.CPY_0
	  WHERE C.CCE_0 = @CCE4 AND C.DIE_0 = @DIE4
 
	  IF @FCYC <> '' OR @FCYF <> @FCY OR @FCYC <> @FCY and @CCE4 <> ''
	  BEGIN
		INSERT INTO #ZTEMP_ERR
		VALUES ('YBB',@BATCHNO,@CCE4,'RESTRICTED DIMENSION')
	  END

    FETCH NEXT FROM BBFCY_CURSOR INTO @BATCHNO, @FCY, @GTE, @JOU,@CCE0, @CCE1, @CCE2, @CCE3, @CCE4   
END 

CLOSE BBFCY_CURSOR  
DEALLOCATE BBFCY_CURSOR 

SELECT * FROM #ZTEMP_ERR

DROP TABLE #ZTEMP_ERR